FROM node:20-alpine

# Create app directory (for use / instead of  /app)
WORKDIR /app

# Install app dependencies
COPY package.json /

RUN npm install

# Bundle app source
COPY . .

RUN npm run build

EXPOSE 3005

CMD [ "npm", "start" ]
